import Foundation
import Combine
import Security

// MARK: - Pure Swift domain types (profiles, library, watched)
// Formerly generated by a NuvioCore FFI layer; the tvOS app is pure Swift now.

/// Profile identity used by profile picker and account sync.
public struct Profile: Equatable, Hashable, Identifiable {
    public var id: String
    public var name: String
    public var isPinProtected: Bool
    public var isAdmin: Bool
    public var avatarId: String
    public var usesPrimaryAddons: Bool
    public var usesPrimaryPlugins: Bool

    public init(
        id: String,
        name: String,
        isPinProtected: Bool = false,
        isAdmin: Bool = false,
        avatarId: String = "",
        usesPrimaryAddons: Bool = false,
        usesPrimaryPlugins: Bool = false
    ) {
        self.id = id
        self.name = name
        self.isPinProtected = isPinProtected
        self.isAdmin = isAdmin
        self.avatarId = avatarId
        self.usesPrimaryAddons = usesPrimaryAddons
        self.usesPrimaryPlugins = usesPrimaryPlugins
    }
}

/// Lightweight meta row used by Library and Search view-models.
public struct StremioMeta: Equatable, Hashable, Identifiable {
    public var id: String
    public var name: String
    public var contentType: String
    public var poster: String?
    public var background: String?
    public var logo: String?
    public var description: String?
    public var releaseInfo: String?
    public var imdbRating: String?
    public var year: Int32?
    public var genres: [String]?
    public var runtime: String?

    public init(id: String, name: String, contentType: String, poster: String? = nil,
                background: String? = nil, logo: String? = nil, description: String? = nil,
                releaseInfo: String? = nil, imdbRating: String? = nil, year: Int32? = nil,
                genres: [String]? = nil, runtime: String? = nil) {
        self.id = id
        self.name = name
        self.contentType = contentType
        self.poster = poster
        self.background = background
        self.logo = logo
        self.description = description
        self.releaseInfo = releaseInfo
        self.imdbRating = imdbRating
        self.year = year
        self.genres = genres
        self.runtime = runtime
    }
}

/// Watched progress row used by continue-watching style surfaces.
public struct WatchedItem: Equatable, Hashable, Identifiable {
    public var id: String
    public var metaId: String
    public var metaType: String
    public var progressPercent: Double
    public var lastWatched: Int64

    public init(id: String, metaId: String, metaType: String, progressPercent: Double, lastWatched: Int64) {
        self.id = id
        self.metaId = metaId
        self.metaType = metaType
        self.progressPercent = progressPercent
        self.lastWatched = lastWatched
    }
}

// MARK: - ProfileManager

/// Pure Swift profile store and selection state.
public class ProfileManager {
    static let profilesChangedNotification = Notification.Name("nuvio.tv.profiles.changed")

    private static let profilesKey = "nuvio.profiles"
    private static let activePinKey = "nuvio.active_profile_id"
    private static let maxProfiles = 6
    private static let maxProfileIdCharacters = 64
    private static let maxProfileNameCharacters = 80
    private static let maxAvatarIdCharacters = 128

    private let profilesURL: URL?

    public init(baseDir: String) throws {
        ProfilePinStore.prepareForUse()
        let baseURL = URL(fileURLWithPath: baseDir, isDirectory: true)
        try FileManager.default.createDirectory(at: baseURL, withIntermediateDirectories: true)
        profilesURL = baseURL.appendingPathComponent("nuvio-profiles.json")
        try migrateProfilesFromUserDefaultsIfNeeded()
        UserDefaults.standard.removeObject(forKey: Self.profilesKey)
    }

    private init(userDefaultsBacked: Void) {
        ProfilePinStore.prepareForUse()
        profilesURL = nil
    }

    fileprivate static func userDefaultsBacked() -> ProfileManager {
        ProfileManager(userDefaultsBacked: ())
    }

    public func getProfiles() throws -> [Profile] {
        do {
            let data: Data
            if let profilesURL {
                guard FileManager.default.fileExists(atPath: profilesURL.path) else {
                    return []
                }
                data = try Data(contentsOf: profilesURL)
            } else {
                guard let stored = UserDefaults.standard.data(forKey: Self.profilesKey) else {
                    return []
                }
                data = stored
            }

            let decoded = try JSONDecoder().decode([StoredProfile].self, from: data)
            let rawProfiles = decoded.map { $0.toProfile() }
            let profiles = Self.sanitizedProfiles(rawProfiles).map { profile in
                var profile = profile
                // A profile can be protected by the account-level PIN service
                // even when this Apple TV has no locally cached PIN secret.
                profile.isPinProtected = profile.isPinProtected || ProfilePinStore.hasPin(for: profile.id)
                return profile
            }
            if profiles != rawProfiles {
                try writeProfiles(profiles)
            }
            return profiles
        } catch {
            quarantineUnreadableProfilesFile()
            return []
        }
    }

    public func createProfile(input: CreateProfileInput) throws -> Profile {
        var profiles = (try? getProfiles()) ?? []
        let id = nextProfileId(in: profiles)
        let pin = try Self.validatedPin(input.pin)
        let profile = Profile(
            id: id,
            name: input.name,
            isPinProtected: pin != nil,
            isAdmin: false,
            avatarId: input.avatarId ?? ""
        )
        profiles.append(profile)
        if let pin {
            try ProfilePinStore.save(pin, for: id)
        }
        do {
            try saveProfiles(profiles)
        } catch {
            if pin != nil { try? ProfilePinStore.removePin(for: id) }
            throw error
        }
        return profile
    }

    public func getActiveProfile() throws -> Profile? {
        let profiles = (try? getProfiles()) ?? []
        if let id = UserDefaults.standard.string(forKey: Self.activePinKey),
           let activeProfile = profiles.first(where: { $0.id == id }) {
            return activeProfile
        }
        return profiles.first
    }

    public func switchProfile(id: String) throws {
        UserDefaults.standard.set(Self.sanitizedProfileId(id), forKey: Self.activePinKey)
    }

    public func deleteProfile(id: String) throws {
        var profiles = (try? getProfiles()) ?? []
        profiles.removeAll(where: { $0.id == id })
        try saveProfiles(profiles)
        try? ProfilePinStore.removePin(for: id)
    }

    public func updateProfileAvatar(id: String, avatarId: String) throws {
        var profiles = (try? getProfiles()) ?? []
        guard let index = profiles.firstIndex(where: { $0.id == id }) else { return }
        profiles[index].avatarId = avatarId
        try saveProfiles(profiles)
    }

    public func updateProfileName(id: String, name: String) throws {
        var profiles = (try? getProfiles()) ?? []
        guard let index = profiles.firstIndex(where: { $0.id == id }) else { return }
        profiles[index].name = name
        try saveProfiles(profiles)
    }

    public func updateProfilePin(id: String, pin: String?) throws {
        var profiles = (try? getProfiles()) ?? []
        guard let index = profiles.firstIndex(where: { $0.id == id }) else { return }

        let pin = try Self.validatedPin(pin)
        let previousPin = ProfilePinStore.pin(for: id)
        if let pin {
            try ProfilePinStore.save(pin, for: id)
        } else {
            try ProfilePinStore.removePin(for: id)
        }
        profiles[index].isPinProtected = pin != nil

        do {
            try saveProfiles(profiles)
        } catch {
            if let previousPin {
                try? ProfilePinStore.save(previousPin, for: id)
            } else {
                try? ProfilePinStore.removePin(for: id)
            }
            throw error
        }
    }

    /// Updates the locally persisted lock flag after the authenticated account
    /// PIN service confirms a set/clear operation. The server owns the secret;
    /// tvOS only needs the flag to decide whether to present the PIN prompt.
    public func setProfilePinProtection(id: String, isProtected: Bool) throws {
        var profiles = (try? getProfiles()) ?? []
        guard let index = profiles.firstIndex(where: { $0.id == id }) else { return }
        if !isProtected {
            try? ProfilePinStore.removePin(for: id)
        }
        profiles[index].isPinProtected = isProtected
        try saveProfiles(profiles)
    }

    public func replaceProfiles(_ profiles: [Profile]) throws {
        let previousIds = Set(((try? getProfiles()) ?? []).map(\.id))
        let profiles = Self.sanitizedProfiles(profiles).map { profile in
            var profile = profile
            profile.isPinProtected = profile.isPinProtected || ProfilePinStore.hasPin(for: profile.id)
            return profile
        }
        try saveProfiles(profiles)
        let retainedIds = Set(profiles.map(\.id))
        for removedId in previousIds.subtracting(retainedIds) {
            try? ProfilePinStore.removePin(for: removedId)
        }
        if let activeId = UserDefaults.standard.string(forKey: Self.activePinKey),
           profiles.contains(where: { $0.id == activeId }) {
            return
        }
        if let first = profiles.first {
            UserDefaults.standard.set(first.id, forKey: Self.activePinKey)
        }
    }

    public func verifyPin(id: String, pin: String) throws -> Bool {
        guard let storedPin = ProfilePinStore.pin(for: id) else { return false }
        return Self.constantTimeEquals(storedPin, pin)
    }

    public func hasPin(id: String) -> Bool {
        ProfilePinStore.hasPin(for: id)
    }

    private func saveProfiles(_ profiles: [Profile]) throws {
        try writeProfiles(profiles)
        NotificationCenter.default.post(name: Self.profilesChangedNotification, object: nil)
    }

    private func writeProfiles(_ profiles: [Profile]) throws {
        let stored = Self.sanitizedProfiles(profiles).map { StoredProfile(from: $0) }
        let data = try JSONEncoder().encode(stored)
        if let profilesURL {
            try data.write(to: profilesURL, options: [.atomic])
        } else {
            UserDefaults.standard.set(data, forKey: Self.profilesKey)
        }
    }

    private func migrateProfilesFromUserDefaultsIfNeeded() throws {
        guard let profilesURL,
              !FileManager.default.fileExists(atPath: profilesURL.path),
              let data = UserDefaults.standard.data(forKey: Self.profilesKey),
              let decoded = try? JSONDecoder().decode([StoredProfile].self, from: data) else {
            return
        }

        try writeProfiles(decoded.map { $0.toProfile() })
        UserDefaults.standard.removeObject(forKey: Self.profilesKey)
    }

    private func quarantineUnreadableProfilesFile() {
        guard let profilesURL else {
            UserDefaults.standard.removeObject(forKey: Self.profilesKey)
            return
        }
        let backupURL = profilesURL.deletingPathExtension().appendingPathExtension("invalid.json")
        try? FileManager.default.removeItem(at: backupURL)
        try? FileManager.default.moveItem(at: profilesURL, to: backupURL)
    }

    private static func sanitizedProfiles(_ profiles: [Profile]) -> [Profile] {
        Array(profiles.prefix(maxProfiles)).map { profile in
            Profile(
                id: sanitizedProfileId(profile.id),
                name: sanitizedProfileName(profile.name),
                isPinProtected: profile.isPinProtected,
                isAdmin: profile.isAdmin,
                avatarId: sanitizedAvatarId(profile.avatarId),
                usesPrimaryAddons: profile.usesPrimaryAddons,
                usesPrimaryPlugins: profile.usesPrimaryPlugins
            )
        }
    }

    private func nextProfileId(in profiles: [Profile]) -> String {
        let used = Set(profiles.compactMap { Int($0.id) })
        if let next = (1...Self.maxProfiles).first(where: { !used.contains($0) }) {
            return String(next)
        }
        return UUID().uuidString
    }

    private static func sanitizedProfileId(_ id: String) -> String {
        let trimmed = id.trimmingCharacters(in: .whitespacesAndNewlines)
        let fallback = UUID().uuidString
        let value = trimmed.isEmpty ? fallback : trimmed
        return String(value.prefix(maxProfileIdCharacters))
    }

    private static func sanitizedProfileName(_ name: String) -> String {
        let trimmed = name.trimmingCharacters(in: .whitespacesAndNewlines)
        let value = trimmed.isEmpty ? "Nuvio User" : trimmed
        return String(value.prefix(maxProfileNameCharacters))
    }

    private static func sanitizedAvatarId(_ avatarId: String) -> String {
        let trimmed = avatarId.trimmingCharacters(in: .whitespacesAndNewlines)
        let lowercased = trimmed.lowercased()
        guard trimmed.count <= maxAvatarIdCharacters,
              !lowercased.hasPrefix("data:"),
              !lowercased.contains("base64,") else {
            return ""
        }
        return trimmed
    }

    private static func validatedPin(_ pin: String?) throws -> String? {
        guard let pin else { return nil }
        let bytes = Array(pin.utf8)
        guard bytes.count == 4, bytes.allSatisfy({ (48...57).contains($0) }) else {
            throw ProfilePinError.invalidFormat
        }
        return pin
    }

    private static func constantTimeEquals(_ lhs: String, _ rhs: String) -> Bool {
        let lhsBytes = Array(lhs.utf8)
        let rhsBytes = Array(rhs.utf8)
        guard lhsBytes.count == rhsBytes.count else { return false }
        var difference: UInt8 = 0
        for (left, right) in zip(lhsBytes, rhsBytes) {
            difference |= left ^ right
        }
        return difference == 0
    }
}

private enum ProfilePinError: LocalizedError {
    case invalidFormat
    case keychain(OSStatus)

    var errorDescription: String? {
        switch self {
        case .invalidFormat:
            return "The profile PIN must contain exactly four digits."
        case .keychain:
            return "The profile PIN could not be saved securely."
        }
    }
}

/// PINs are device-local and kept in the Keychain; profile/account sync never
/// receives the secret. The UserDefaults marker clears orphaned Keychain items
/// after an app reinstall, when the profile database no longer exists.
private enum ProfilePinStore {
    private static let service = "com.nuvio.tv.profile-pin"
    private static let initializedKey = "nuvio.profilePins.keychainInitialized"

    static func prepareForUse() {
        guard !UserDefaults.standard.bool(forKey: initializedKey) else { return }
        SecItemDelete([
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: service
        ] as CFDictionary)
        UserDefaults.standard.set(true, forKey: initializedKey)
    }

    static func hasPin(for profileId: String) -> Bool {
        pin(for: profileId) != nil
    }

    static func pin(for profileId: String) -> String? {
        var query = keychainQuery(for: profileId)
        query[kSecReturnData as String] = kCFBooleanTrue
        query[kSecMatchLimit as String] = kSecMatchLimitOne

        var item: CFTypeRef?
        guard SecItemCopyMatching(query as CFDictionary, &item) == errSecSuccess,
              let data = item as? Data else { return nil }
        return String(data: data, encoding: .utf8)
    }

    static func save(_ pin: String, for profileId: String) throws {
        let data = Data(pin.utf8)
        var addQuery = keychainQuery(for: profileId)
        addQuery[kSecAttrAccessible as String] = kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly
        addQuery[kSecValueData as String] = data

        let status = SecItemAdd(addQuery as CFDictionary, nil)
        if status == errSecDuplicateItem {
            let updateStatus = SecItemUpdate(
                keychainQuery(for: profileId) as CFDictionary,
                [kSecValueData as String: data] as CFDictionary
            )
            guard updateStatus == errSecSuccess else { throw ProfilePinError.keychain(updateStatus) }
        } else if status != errSecSuccess {
            throw ProfilePinError.keychain(status)
        }
    }

    static func removePin(for profileId: String) throws {
        let status = SecItemDelete(keychainQuery(for: profileId) as CFDictionary)
        guard status == errSecSuccess || status == errSecItemNotFound else {
            throw ProfilePinError.keychain(status)
        }
    }

    private static func keychainQuery(for profileId: String) -> [String: Any] {
        [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: service,
            kSecAttrAccount as String: profileId
        ]
    }
}

// Codable helper for UserDefaults persistence
private struct StoredProfile: Codable {
    var id: String
    var name: String
    var isPinProtected: Bool
    var isAdmin: Bool
    var avatarId: String
    var usesPrimaryAddons: Bool?
    var usesPrimaryPlugins: Bool?

    init(from profile: Profile) {
        self.id = profile.id
        self.name = profile.name
        self.isPinProtected = profile.isPinProtected
        self.isAdmin = profile.isAdmin
        self.avatarId = profile.avatarId
        self.usesPrimaryAddons = profile.usesPrimaryAddons
        self.usesPrimaryPlugins = profile.usesPrimaryPlugins
    }

    func toProfile() -> Profile {
        Profile(
            id: id,
            name: name,
            isPinProtected: isPinProtected,
            isAdmin: isAdmin,
            avatarId: avatarId,
            usesPrimaryAddons: usesPrimaryAddons ?? false,
            usesPrimaryPlugins: usesPrimaryPlugins ?? false
        )
    }
}

/// Input for creating a profile
public struct CreateProfileInput {
    public var name: String
    public var profileType: ProfileTypeStub
    public var avatarId: String?
    public var maxAgeRating: String?
    public var pin: String?

    public init(name: String, profileType: ProfileTypeStub = .adult, avatarId: String? = nil, maxAgeRating: String? = nil, pin: String? = nil) {
        self.name = name
        self.profileType = profileType
        self.avatarId = avatarId
        self.maxAgeRating = maxAgeRating
        self.pin = pin
    }
}

public enum ProfileTypeStub {
    case admin, adult, kids
}

// Alias so ProfileViewModel can use .admin / .adult without changes
typealias ProfileType = ProfileTypeStub

// MARK: - ProfileViewModel

@MainActor
public class ProfileViewModel: ObservableObject {
    @Published public var profiles: [Profile] = []
    @Published public var activeProfile: Profile?
    @Published public var isPinEntryVisible = false
    @Published public var pinError: String?
    @Published public var profileCreationError: String?
    @Published public var isLoading = false
    @Published public var pendingProfileId: String?

    /// Fires only when the user explicitly picks a profile (who's-watching
    /// card or PIN confirmation) — never when a sync refreshes
    /// `activeProfile`. Screens navigate on this, not on `$activeProfile`.
    public let profileChosen = PassthroughSubject<Profile, Never>()

    private let profileManager: ProfileManager?
    private var profilesObserver: Any?
    private var remotePinVerifier: ((String, String) async throws -> Bool)?

    public init(profileManager: ProfileManager? = nil) {
        if let manager = profileManager {
            self.profileManager = manager
        } else {
            do {
                self.profileManager = try Self.makeDefaultProfileManager()
            } catch {
                print("Failed to initialize ProfileManager: \(error)")
                // A profile picker must never become a read-only shell. Some
                // unsigned/sideload signing combinations expose no writable
                // file URL even though app preferences remain persistent.
                self.profileManager = ProfileManager.userDefaultsBacked()
            }
        }
        loadProfiles()
        loadActiveProfile()

        // Reload when sync (or any other path) writes new profiles so the
        // Who's-Watching screen updates live after login / first sync.
        profilesObserver = NotificationCenter.default.addObserver(
            forName: ProfileManager.profilesChangedNotification,
            object: nil,
            queue: .main
        ) { [weak self] _ in
            Task { @MainActor [weak self] in
                self?.loadProfiles()
                self?.loadActiveProfile()
            }
        }
    }

    /// Resolves profile storage without relying on
    /// `FileManager.url(for:in:appropriateFor:create:)`. That API can throw for
    /// Application Support in some physical-tvOS sideload containers even when
    /// the app's Library directory is writable. Try persistent sandbox
    /// locations in order and verify them with a real atomic write before use.
    private static func makeDefaultProfileManager(fileManager: FileManager = .default) throws -> ProfileManager {
        var candidates: [URL] = []

        if let applicationSupport = fileManager.urls(
            for: .applicationSupportDirectory,
            in: .userDomainMask
        ).first {
            candidates.append(applicationSupport.appendingPathComponent("Nuvio", isDirectory: true))
        }

        let homeLibrary = URL(fileURLWithPath: NSHomeDirectory(), isDirectory: true)
            .appendingPathComponent("Library", isDirectory: true)
        candidates.append(
            homeLibrary
                .appendingPathComponent("Application Support", isDirectory: true)
                .appendingPathComponent("Nuvio", isDirectory: true)
        )
        candidates.append(homeLibrary.appendingPathComponent("Nuvio", isDirectory: true))

        let documentsURL = fileManager.urls(for: .documentDirectory, in: .userDomainMask).first
        if let documentsURL {
            candidates.append(documentsURL.appendingPathComponent("Nuvio", isDirectory: true))
        }

        var attemptedPaths = Set<String>()
        var lastError: Error?

        for candidate in candidates {
            let path = candidate.standardizedFileURL.path
            guard attemptedPaths.insert(path).inserted else { continue }

            do {
                try fileManager.createDirectory(at: candidate, withIntermediateDirectories: true)

                let probeURL = candidate.appendingPathComponent(".profile-storage-probe-\(UUID().uuidString)")
                try Data().write(to: probeURL, options: .atomic)
                try? fileManager.removeItem(at: probeURL)

                // Keep profiles from development/older builds when that file
                // is readable, but never make startup depend on Documents.
                let profilesURL = candidate.appendingPathComponent("nuvio-profiles.json")
                if let documentsURL {
                    let legacyURL = documentsURL.appendingPathComponent("nuvio-profiles.json")
                    if !fileManager.fileExists(atPath: profilesURL.path),
                       fileManager.fileExists(atPath: legacyURL.path) {
                        try? fileManager.copyItem(at: legacyURL, to: profilesURL)
                    }
                }

                return try ProfileManager(baseDir: candidate.path)
            } catch {
                lastError = error
                print("Profile storage unavailable at \(path): \(error)")
            }
        }

        throw lastError ?? CocoaError(.fileNoSuchFile)
    }

    deinit {
        if let observer = profilesObserver {
            NotificationCenter.default.removeObserver(observer)
        }
    }

    public func configureRemotePinVerifier(
        _ verifier: @escaping (String, String) async throws -> Bool
    ) {
        remotePinVerifier = verifier
    }

    public func loadProfiles() {
        guard let manager = profileManager else {
            // Seed a default profile so the UI isn't empty
            if profiles.isEmpty {
                profiles = [
                    Profile(
                        id: "guest",
                        name: "Nuvio Guest",
                        isPinProtected: false,
                        isAdmin: true,
                        avatarId: ""
                    )
                ]
            }
            return
        }
        do {
            var list = try manager.getProfiles()
            if list.isEmpty {
                // Keep the fresh-install placeholder distinct from remote slot
                // 1. Account sync replaces `guest` with the real primary profile
                // instead of preserving the placeholder as account identity.
                try manager.replaceProfiles([
                    Profile(
                        id: "guest",
                        name: "Nuvio Guest",
                        isPinProtected: false,
                        isAdmin: true,
                        avatarId: ""
                    )
                ])
                list = try manager.getProfiles()
            }
            self.profiles = list
        } catch {
            print("Failed to load profiles: \(error)")
        }
    }

    public func loadActiveProfile() {
        guard let manager = profileManager else {
            let profile = profiles.first
            // Scope watch history and settings to this profile before the UI reads them.
            ContinueWatchingStore.setActiveProfile(profile?.id)
            LibraryStore.setActiveProfile(profile?.id)
            WatchedStore.setActiveProfile(profile?.id)
            CollectionsStore.setActiveProfile(profile?.id)
            ProfileSettings.setActiveProfile(profile?.id)
            // Before anything else can write: an oversized preferences
            // plist aborts the process on the next unrelated set.
            SimklSyncCache.purgeLegacyPreferenceBlobs(in: ProfileSettings.current)
            self.activeProfile = profile
            return
        }
        do {
            let profile = try manager.getActiveProfile()
            // Scope watch history and settings to this profile before the UI reads them.
            ContinueWatchingStore.setActiveProfile(profile?.id)
            LibraryStore.setActiveProfile(profile?.id)
            WatchedStore.setActiveProfile(profile?.id)
            CollectionsStore.setActiveProfile(profile?.id)
            ProfileSettings.setActiveProfile(profile?.id)
            // Before anything else can write: an oversized preferences
            // plist aborts the process on the next unrelated set.
            SimklSyncCache.purgeLegacyPreferenceBlobs(in: ProfileSettings.current)
            self.activeProfile = profile
        } catch {
            print("Failed to load active profile: \(error)")
        }
    }

    public func createProfile(
        name: String,
        pin: String?,
        avatarId: String = "",
        onCreated: (() -> Void)? = nil
    ) {
        guard let manager = profileManager else {
            profileCreationError = "Profiles are unavailable on this device."
            return
        }
        guard !isLoading else { return }
        isLoading = true
        profileCreationError = nil
        let input = CreateProfileInput(name: name, profileType: .adult, avatarId: avatarId, pin: pin)
        Task {
            do {
                let newProfile = try manager.createProfile(input: input)
                // Start the new profile as a copy of the current settings; it
                // diverges independently from then on.
                ProfileSettings.seedNewProfile(newProfile.id)
                loadProfiles()
                isLoading = false
                onCreated?()
            } catch {
                profileCreationError = "Couldn't save this profile: \(error.localizedDescription)"
                print("Failed to create profile: \(error)")
                isLoading = false
            }
        }
    }

    public func updateActiveProfileAvatar(_ avatarId: String) {
        guard let id = activeProfile?.id else { return }
        updateProfileAvatar(id: id, avatarId: avatarId)
    }

    public func updateProfileName(id: String, name: String) {
        let name = name.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !name.isEmpty else { return }

        guard let manager = profileManager else {
            if let index = profiles.firstIndex(where: { $0.id == id }) {
                profiles[index].name = name
                if activeProfile?.id == id {
                    activeProfile = profiles[index]
                }
            }
            return
        }

        do {
            try manager.updateProfileName(id: id, name: name)
            loadProfiles()
            loadActiveProfile()
        } catch {
            print("Failed to update profile name: \(error)")
        }
    }

    public func updateProfileAvatar(id: String, avatarId: String) {
        guard !avatarId.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }

        guard let manager = profileManager else {
            if let index = profiles.firstIndex(where: { $0.id == id }) {
                profiles[index].avatarId = avatarId
                if activeProfile?.id == id {
                    activeProfile = profiles[index]
                }
            }
            return
        }

        do {
            try manager.updateProfileAvatar(id: id, avatarId: avatarId)
            loadProfiles()
            loadActiveProfile()
        } catch {
            print("Failed to update profile avatar: \(error)")
        }
    }

    @discardableResult
    public func updateProfilePin(id: String, pin: String?) -> Bool {
        guard let manager = profileManager else { return false }
        do {
            try manager.updateProfilePin(id: id, pin: pin)
            loadProfiles()
            loadActiveProfile()
            return true
        } catch {
            print("Failed to update profile PIN: \(error.localizedDescription)")
            return false
        }
    }

    public func verifyProfilePin(id: String, pin: String) -> Bool {
        do {
            return try profileManager?.verifyPin(id: id, pin: pin) == true
        } catch {
            print("Failed to verify profile PIN: \(error.localizedDescription)")
            return false
        }
    }

    @discardableResult
    public func setProfilePinProtection(id: String, isProtected: Bool) -> Bool {
        guard let manager = profileManager else { return false }
        do {
            try manager.setProfilePinProtection(id: id, isProtected: isProtected)
            loadProfiles()
            loadActiveProfile()
            return true
        } catch {
            print("Failed to update profile PIN protection: \(error.localizedDescription)")
            return false
        }
    }

    public func requestSwitch(to profile: Profile) {
        if profile.isPinProtected {
            self.pendingProfileId = profile.id
            self.isPinEntryVisible = true
        } else {
            switchProfile(id: profile.id, pin: nil)
        }
    }

    public func verifyAndSwitch(pin: String) {
        guard let id = pendingProfileId else { return }
        if profileManager?.hasPin(id: id) == true {
            switchProfile(id: id, pin: pin)
            return
        }

        guard let remotePinVerifier else {
            pinError = "PIN verification is unavailable. Check your connection and try again."
            return
        }

        isLoading = true
        pinError = nil
        Task { @MainActor [weak self] in
            guard let self else { return }
            do {
                let unlocked = try await remotePinVerifier(id, pin)
                self.isLoading = false
                guard unlocked else {
                    self.pinError = "Incorrect PIN"
                    return
                }
                self.completeSwitch(id: id)
            } catch {
                self.isLoading = false
                self.pinError = "Couldn't verify the PIN. Check your connection and try again."
                print("Failed to verify remote profile PIN: \(error.localizedDescription)")
            }
        }
    }

    private func switchProfile(id: String, pin: String?) {
        if profileManager?.hasPin(id: id) == true {
            guard let pin, !pin.isEmpty, verifyProfilePin(id: id, pin: pin) else {
                pinError = "Incorrect PIN"
                return
            }
        }
        completeSwitch(id: id)
    }

    private func completeSwitch(id: String) {
        do {
            try profileManager?.switchProfile(id: id)
            loadActiveProfile()
            isPinEntryVisible = false
            pendingProfileId = nil
            pinError = nil
            if let profile = activeProfile {
                profileChosen.send(profile)
            }
        } catch {
            pinError = "Couldn't switch profiles. Try again."
            print("Failed to switch profile: \(error)")
        }
    }

    @discardableResult
    public func applyRemoteProfiles(_ remoteProfiles: [Profile]) -> Bool {
        guard !remoteProfiles.isEmpty else { return false }
        let preferredActiveId = activeProfile?.id

        guard let manager = profileManager else {
            return applyProfilesInMemory(remoteProfiles, preferredActiveId: preferredActiveId)
        }

        do {
            try manager.replaceProfiles(remoteProfiles)
            if let preferredActiveId,
               remoteProfiles.contains(where: { $0.id == preferredActiveId }) {
                try manager.switchProfile(id: preferredActiveId)
            }
            loadProfiles()
            // Unconditional: besides refreshing the profile object this scopes
            // the watch-state stores (setActiveProfile) so the sync's merges
            // that follow land in the right per-profile buckets. Navigation
            // away from who's-watching listens to `profileChosen`, not
            // `activeProfile`, so this can't yank the user into a profile.
            loadActiveProfile()
            let expectedProfiles = remoteProfiles.map { profile in
                var profile = profile
                profile.isPinProtected = profile.isPinProtected || manager.hasPin(id: profile.id)
                return profile
            }
            guard profiles == expectedProfiles,
                  let activeProfile,
                  profiles.contains(where: { $0.id == activeProfile.id }) else {
                print("Persisted remote profiles did not reload as written; using the pulled profiles in memory.")
                return applyProfilesInMemory(remoteProfiles, preferredActiveId: preferredActiveId)
            }
            return true
        } catch {
            print("Failed to apply remote profiles: \(error)")
            return applyProfilesInMemory(remoteProfiles, preferredActiveId: preferredActiveId)
        }
    }

    private func applyProfilesInMemory(_ remoteProfiles: [Profile], preferredActiveId: String?) -> Bool {
        profiles = remoteProfiles
        let profile = preferredActiveId.flatMap { preferredId in
            remoteProfiles.first(where: { $0.id == preferredId })
        } ?? remoteProfiles.first

        ContinueWatchingStore.setActiveProfile(profile?.id)
        LibraryStore.setActiveProfile(profile?.id)
        WatchedStore.setActiveProfile(profile?.id)
        CollectionsStore.setActiveProfile(profile?.id)
        ProfileSettings.setActiveProfile(profile?.id)
        // Before anything else can write: an oversized preferences
        // plist aborts the process on the next unrelated set.
        SimklSyncCache.purgeLegacyPreferenceBlobs(in: ProfileSettings.current)
        activeProfile = profile

        guard profiles == remoteProfiles, let profile else { return false }
        return profiles.contains(where: { $0.id == profile.id })
    }

    public func resetForSignedOut() {
        let guest = Profile(
            id: "guest",
            name: "Nuvio Guest",
            isPinProtected: false,
            isAdmin: true,
            avatarId: ""
        )
        // Collect ids before replacing the profile list so their settings
        // suites can be deleted below.
        let previousIds = ((try? profileManager?.getProfiles()) ?? profiles).map(\.id)
        do {
            try profileManager?.replaceProfiles([guest])
        } catch {
            print("Failed to reset signed-out profile: \(error)")
        }
        profiles = [guest]
        activeProfile = guest

        // Sign-out is a full local reset: no watch history, watched marks,
        // library items, add-ons, API keys, or preferences may survive into
        // the next session. Remote data stays on the account — the sync
        // manager is already detached (auth state is signed out), so these
        // deletions never push to the server.
        ContinueWatchingStore.eraseAllProfiles()
        LibraryStore.eraseAllProfiles()
        WatchedStore.eraseAllProfiles()
        CollectionsStore.eraseAllProfiles()
        // Cover the whole local id space (1-6 + guest), not just the current
        // list, so suites left behind by previously deleted profiles go too.
        ProfileSettings.eraseAll(profileIds: previousIds + (1...6).map(String.init) + [guest.id])
        NuvioSyncManager.eraseProfileIndexBindings()

        ContinueWatchingStore.setActiveProfile(guest.id)
        LibraryStore.setActiveProfile(guest.id)
        WatchedStore.setActiveProfile(guest.id)
        CollectionsStore.setActiveProfile(guest.id)
        ProfileSettings.setActiveProfile(guest.id)
    }
}

/// Preview/test helper that returns canned catalog search hits.
public class StremioService {
    public init() throws {}

    public func getCatalog(addonId: String, contentType: String, catalogId: String, page: Int32, search: String?) async throws -> [StremioMeta] {
        if let query = search, !query.isEmpty {
            return [
                StremioMeta(id: "mock1", name: "\(query) Result 1", contentType: contentType),
                StremioMeta(id: "mock2", name: "\(query) Result 2", contentType: contentType)
            ]
        }
        return []
    }
}
